language: node_js
os: osx
osx_image: xcode10.1
node_js:
  - "12"
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
cache:
  directories:
    - node_modules
    - $HOME/Library/Caches/Homebrew
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
before_cache:
  - brew cleanup
  - rm -rf $HOME/.cache/electron-builder/wine
install:
  - brew install ghr
  - npm install
before_script:
  - npm run build:web
script:
  - npm run lint:all
  - npm run test
  - npm run release:all
deploy:
  - provider: script
    skip_cleanup: true
    script: /bin/sh travis/release.sh
    on:
      branch: $RELEASE_BRANCH
