language: node_js
node_js:
  - "12"
os: osx
osx_image: xcode11.3
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
before_script:
  - npm run build:web
script:
  - npm run lint:all
  - npm run test
deploy:
  - provider: script
    skip_cleanup: true
    script: /bin/sh travis/release.sh
    on:
      branch: $RELEASE_BRANCH
