language: node_js
os: osx
osx_image: xcode10.1
node_js:
  - "12"
cache:
  directories:
    - node_modules
install:
  - brew install ghr
before_script:
  - npm run build:web
script:
  - npm run lint:all
  - npm run test
  - npm run release:all
deploy:
  - provider: script
    skip_cleanup: true
    script: /bin/sh travis/release.sh
    on:
      branch: $RELEASE_BRANCH
