language: node_js
os: osx
node_js:
  - "12"
cache:
  directories:
    - node_modules
before_script:
  - npm run build:web
script:
  - npm run lint:all
  - npm run test
  - npm run release:all
deploy:
  - provider: script
    skip_cleanup: true
    script: /bin/sh travis/release.sh
    on:
      branch: $RELEASE_BRANCH
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file:
      - release/symbol-desktop-wallet-win.exe
      - release/symbol-desktop-wallet-linux-x64.tar.xz
      - release/symbol-desktop-wallet-linux-amd64.snap
      - release/symbol-desktop-wallet-linux-amd64.deb
      - release/symbol-desktop-wallet-mac.dmg
    on:
      tags: true
